
//GET http://localhost:4004/odata/v4/manage-orders/GetOrders

GET http://localhost:4004/odata/v4/manage-orders/GetOrders('client2@client2.com')

### Create Order
POST http://localhost:4004/odata/v4/manage-orders/CreateOrder HTTP/1.1
Content-Type: application/json
{
        "ClientEmail" : "client5@client5",
        "FirstName"   : "Lorena",
        "LastName"    : "Gracias",
        "CreatedOn"   : "2024-10-10"
}

### Update Order
PUT http://localhost:4004/odata/v4/manage-orders/UpdateOrder('client1@client1.com') HTTP/1.1
Content-Type: application/json
{
        "FirstName"   : "Lorena Update",
        "LastName"    : "Gracias Update"
}

### Delete Order
DELETE http://localhost:4004/odata/v4/manage-orders/DeleteOrder('client1@client1.com')

### Get Customer Rate - 
get http://localhost:4004/odata/v4/manage-orders/getClientTaxRate(clientEmail='client2@client2.com')


### Cancel Order - Action
POST  http://localhost:4004/odata/v4/manage-orders/cancelOrder
Content-Type: application/json

{
   "clientEmail" : "client1@client1.com"     
}







### Get Customer Rate 
get http://localhost:4004/odata/v4/manage-orders/Orders('client1@client1.com')/ManageOrders.getClientTaxRate(clientEmail='client2@client2.com')


### Cancel Order - Action
POST  http://localhost:4004/odata/v4/manage-orders/Orders('client1@client1.com')/ManageOrders.cancelOrder
Content-Type: application/json

{
   "clientEmail" : "client1@client1.com"     
}

### Get Insident
GET http://localhost:4004/odata/v4/sapbackend-exit/Incidents